# Generated by Django 4.2.8 on 2024-08-07 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo',
            field=models.CharField(choices=[('PC', 'PC Escritorio'), ('Notebook', 'Notebook'), ('Impresora', 'Impresora'), ('Scanner', 'Scanner')], default='PC Escritorio', max_length=50),
        ),
    ]
